services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: Chefcito
      POSTGRES_PASSWORD: Laboratorio1.
      POSTGRES_DB: ChefcitoDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

  app:
    build: ./app
    environment:
      DATABASE_URL: postgres://Chefcito:Laboratorio1.@postgres:5432/ChefcitoDb
    depends_on:
      - postgres
    networks:
      - my_network
    ports:
      - "3000:3000"

volumes:
  postgres_data:

networks:
  my_network:
